FROM balenalib/raspberry-pi-python:3.8.2-stretch-build

RUN install_packages git

WORKDIR /usr/src/app

COPY requirements.txt requirements.txt

RUN apt-get clean && apt-get update && apt-get install -yq \
	build-essential libffi-dev libssl-dev \
    && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt

COPY . ./

ENV UDEV=1

# CMD [ "cat", "requirements.txt"]
CMD [ "python", "-u", "src/helloworld.py" ]
